interactivepuzzle/urls.py
from django.urls import path

from . import views

app_name = "interactivepuzzle"

urlpatterns = [
    path("", views.index, name="index"),
    path("register/", views.register_request, name="register"),
    path("login/", views.login_request, name="login"),
    path("logout/", views.logout_request, name="logout"),
    path("instructions/", views.instructions, name="instructions"),
    path("question", views.fetchquestion, name="fetchquestion"),
    path("submission/<int:id>/", views.submission_request, name="submission"),
    path("leaderboard/", views.fetch_leaderboard, name="leaderboard"),
    path("analytics/", views.get_analytics, name="analytics")
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include("interactivepuzzle.urls")),
    path('admin/', admin.site.urls),
]

interactivepuzzle/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
import datetime


class CustomUser(AbstractUser):
    took_test = models.BooleanField(default=False)
    accuracy = models.FloatField(default=0)
    lives = models.IntegerField(default=3)


class question(models.Model):
    question_title = models.CharField(max_length=500)
    question_text = models.CharField(max_length=800)
    question_description = models.CharField(max_length=4000)
    clues = models.CharField(max_length=4000)
    pub_date = models.DateTimeField("date published")
    answer = models.CharField(max_length=400, default="Default Answer")
    image = models.CharField(max_length=1000)


class session(models.Model):
    question = models.ForeignKey(question, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    startTime = models.DateTimeField()
    endTime = models.DateField(null=True)


class submissions(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    question = models.ForeignKey(question, on_delete=models.CASCADE)
    status = models.SmallIntegerField(default=0)
    timeStart = models.DateTimeField()
    timeEnd = models.DateTimeField()
    score = models.FloatField(default=0)

interactivepuzzle/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()
class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

interactivepuzzle/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from .forms import NewUserForm
from .models import submissions, CustomUser, question, session
import datetime
from django.utils import timezone


def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful!",
                             extra_tags='login_success')
            return redirect("interactivepuzzle:index")
        messages.error(
            request, "Unsuccessful registration. Invalid information.", extra_tags='registration_failure')
    form = NewUserForm()
    return render(request=request, template_name="register.html", context={"register_form": form})


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(
                    request, f"Successfully logged in as {username}!", extra_tags="login_success")
                return redirect("interactivepuzzle:index")
            else:
                messages.error(
                    request, "Invalid username or password.", extra_tags="login_failure")
        else:
            messages.error(request, "Invalid username or password.",
                           extra_tags="login_failure")
    form = AuthenticationForm()
    return render(request=request, template_name="login.html", context={"login_form": form})


def index(request):
    if request.user.is_authenticated:
        return render(request, 'index.html')
    return login_request(request)


def logout_request(request):
    if request.user.is_authenticated:
        logout(request)
    return login_request(request)


def instructions(request):
    if request.user.is_authenticated:
        return render(request, 'instructions.html')
    return login_request(request)


def fetchquestion(request):
    if request.user.is_authenticated:
        ques = question.objects.all()
        user = CustomUser.objects.get(username=request.user)
        if user.took_test:
            return render(request, 'deadend.html')
        subs = submissions.objects.filter(
            user=request.user).filter(status=True)
        currQuestion = len(subs) + 1
        if currQuestion > len(ques):
            return get_analytics(request)
        que = question.objects.filter(id=currQuestion)
        createSession = False
        for q in que:
            que = q
            createSession = True
            break
        user_session = session.objects.filter(user=request.user)
        if len(user_session) != 0:
            user_session = user_session.filter(question=que)
            found = False
            for u in user_session:
                user_session = u
                found = True
                break
            if not found:
                user_session = session()
                user_session.user = user
                user_session.question = que
                user_session.startTime = timezone.now()

                user_session.save()
            arr = q.clues.split('>')
            que.clues = arr
            return render(request, 'question.html', context={'question': que, 'session': user_session})
        if len(user_session) == 0 and createSession:
            # create a new session for the question
            user_session = session()
            user_session.question = que
            user_session.user = user
            user_session.startTime = timezone.now()
            user_session.save()

        arr = q.clues.split('>')
        que.clues = arr
        return render(request, 'question.html', context={'question': que, 'session': user_session})
    return login_request(request)


def submission_request(request, id):
    if request.GET:
        return fetchquestion(request)
    if request.user.is_authenticated:
        usr = CustomUser.objects.get(username=request.user)
        if usr.took_test:
            return render(request, 'deadend.html')
        currQuestion = submissions.objects.filter(
            user=request.user).filter(status=True)
        currQuestionId = len(currQuestion) + 1
        if id != currQuestionId:
            return fetchquestion(request)
        else:
            data = request.POST.dict()
            answer = data.get("answer")
            user = CustomUser.objects.get(username=request.user)
            quesdata = question.objects.get(id=id)
            if answer == '':
                return fetchquestion(request)
            if quesdata.answer == answer:
                prevSession = session.objects.filter(
                    user=request.user).filter(question=quesdata)
                currSubmission = submissions()
                currSubmission.question = quesdata
                currSubmission.user = user
                currSubmission.status = True
                for s in prevSession:
                    currSubmission.timeStart = s.startTime
                    break
                currSubmission.timeEnd = timezone.now()
                currSubmission.score = 100
                currSubmission.save()
                for s in prevSession:
                    prevSession = s
                prevSession.endTime = timezone.now()
                prevSession.save()
                return fetchquestion(request)
            else:
                currSubmission = submissions()
                currSubmission.question = quesdata
                currSubmission.user = user
                currSubmission.status = False
                currSubmission.timeStart = timezone.now()
                currSubmission.timeEnd = timezone.now()
                currSubmission.score = 0
                currSubmission.save()
                subs = submissions.objects.filter(
                    user=user).filter(question=quesdata)
                chances = 3 - len(subs)
                if chances == 0:
                    currUser = CustomUser.objects.get(username=request.user)
                    currUser.took_test = True
                    currUser.save()
                    return render(request, 'deadend.html')
                messages.info(
                    request, f"{answer} is the Wrong Answer :( {chances} more lives!", extra_tags="wrong_submission")
                return fetchquestion(request)
    return login_request(request)


def fetch_leaderboard(request):
    subs = submissions.objects.filter(status=True)
    users = CustomUser.objects.all()
    userData = {}
    for user in users:
        userData[user.username] = {'score': 0, 'time': 0}
    for sub in subs:
        userData[sub.user.username]['score'] = userData[sub.user.username]['score'] + sub.score
        timeTaken = sub.timeEnd - sub.timeStart
        userData[sub.user.username]['time'] = int(
            userData[sub.user.username]['time'] + (timeTaken.seconds)/60)
    sorted_data = sorted(
        userData.items(), key=lambda x: (-1*x[1]['score'], x[1]['time']))
    final_data = []
    for data in sorted_data:
        final_data.append([data[0], data[1]['score'], data[1]['time']])
    context = {'data': final_data}
    return render(request, 'leaderboard.html', context=context)


def get_analytics(request):
    queData = question.objects.all()
    user = CustomUser.objects.get(username=request.user)

    userData = []
    # score,submissions,time,accuracy,status
    for que in queData:
        subs = submissions.objects.filter(user=user).filter(question=que)
        if len(subs) == 0:
            userData.append([0, 0, 0, 0, 'UnAttempted'])
        else:
            ac = submissions.objects.filter(user=user).filter(
                question=que).filter(status=True)
            if len(ac) == 0:
                currSession = session.objects.get(user=user, question=que)
                timedelta = timezone.now() - currSession.startTime
                timeTaken = int(timedelta.seconds/60)
                userData.append([0, len(subs), timeTaken, 0, 'Wrong Answer'])
            else:
                lastSub = submissions.objects.get(
                    user=user, question=que, status=True)
                timedelta = lastSub.timeEnd - lastSub.timeStart
                timeTaken = int(timedelta.seconds/60)
                userData.append([100, len(subs), timeTaken,
                                int(100/(len(subs))), 'Accepted'])
    context = {'data': userData}
    return render(request, 'Analytics.html', context=context)

interactivepuzzle/templates/Analytics.html
{% extends "header.html" %} {% block content %} {% load crispy_forms_tags %}
{% load static %}
<script src="https://cdn.anychart.com/releases/8.10.0/js/anychart-base.min.js"></script>
<style>
    .a_accuracy,
    .a_count,
    .a_timename,
    .a_status,
    .a_score {
        text-align: center;
    }

    #container {
        width: 100%;
        height: 50vh;
    }

    @media screen and (max-width:950px) {
        .a_timename {
            display: none;
        }

        h1 {
            font-size: 1.5rem;
        }
    }

    @media screen and (max-width:950px) {
        .a_accuracy {
            display: none;
        }
    }
</style>
<div class="leaderboard-container">
    {% if user.is_authenticated %}
    <main>
        <div id="header">
            <h1>Score Board</h1>
        </div>
        <div id="leaderboard">
            <table>
                <tr>
                    <td class="a_count">Que No.</td>
                    <td class="a_score">Score</td>
                    <td class="a_timename">Time (min)</td>
                    <td class="a_accuracy">Accuracy (%)</td>
                    <td class="a_status">Status</td>
                </tr>
                {% for sublist in data %}
                <tr>
                    <td class="a_count">{{forloop.counter}}</td>
                    <td class="a_score">{{sublist.0}}</td>
                    <td class="a_timename">{{sublist.2}}</td>
                    <td class="a_accuracy">
                        {{sublist.3}}
                    </td>
                    <td class="a_status">
                        {% if sublist.4 == 'Accepted' %}
                        AC
                        {% elif sublist.4 == 'Wrong Answer' %}
                        WA
                        {% else %}
                        NA
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </main>
    {% endif %}
</div>
<div class="leaderboard-container" style="display: flex;flex-direction: column;">
    {% if user.is_authenticated %}
    <h1>Accuracy throughout the questions</h1>
    <div id="container"></div>
    {% endif %}
</div>
<script>
    function getData() {
        var data = []
        const backendData = "{{data}}"
        mydata = backendData.split(",")
        let st = 3
        do {
            let num = parseInt(mydata[st], 10);
            data.push(num)
            st += 5;
        } while (st < mydata.length)
        var finalData = []
        for (let i = 1; i <= data.length; i++) {
            finalData.push([i, data[i]])
        }
        return finalData;
    }
    var dataSet = anychart.data.set(getData());
    var seriesData = dataSet.mapAs({ x: 0, value: 1 });
    var chart = anychart.line();
    chart.title('Accuracy vs Question');
    chart.yAxis().title('% of Accuracy');
    var lineChart = chart.line(seriesData);
    chart.container('container');
    chart.draw();
</script>
{% endblock %}

interactivepuzzle/templates/deadend.html
{% extends 'header.html' %} {% block content %}
<div class="leaderboard-container">
    <section class="question_container">
        <figure>
            <img src="https://m.media-amazon.com/images/M/MV5BMjgzNzNlMDctMWVhZC00ZTVmLWI2MjMtYjdhNmFjNDQxNDRiL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjM2NDIwMzQ@._V1_.jpg"
                alt="Reached DeadEnd" style="width:-webkit-fill-available;height: fit-content;">
        </figure>
    </section>
</div>
{% endblock %}

interactivepuzzle/templates/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/header.css' %}" />
  <script>
    const startTime = "{{session.startTime}}";
  </script>
  <!-- Bootstrap CSS -->
  
  <script src="https://kit.fontawesome.com/c138ede282.js" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/@phosphor-icons/web"></script>
  <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@400;500&display=swap" rel="stylesheet" />
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />
  <title>Interactive Quiz</title>
</head>

<body>
  <div style="min-height:100vh; display:flex; flex-direction:column; 
            justify-content:space-between;">
    {% include "includes/navbar.html" %}
    <section class="content_section">
      {% block content %} {% endblock %}
    </section>
    {% include "includes/footer.html" %}
    <script>
      if (document.querySelector('.js-alert')) {
        document.querySelectorAll('.js-alert').forEach(function ($el) {
          setTimeout(() => {
            $el.style.display = 'none';
          }, 2000);
        });
      }
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
    <script src="{% static 'js/timer.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"></script>
  </div>
</body>

</html>

interactivepuzzle/templates/index.html
{% extends 'header.html' %} {% block content %}
<style>
  .index-container {
    display: flex;
    width: 80vw;
    min-height: 80vh;
    margin: 2vh auto;
    flex-direction: column;
    align-items: center;
    justify-content: center;
  }

  .username {
    font-size: 2rem;
    color: rgb(255, 255, 255);
    padding: 1vh 1vw;
    margin: 1vh 1vw;
  }

  .des {
    font-size: 1rem;
    color: floralwhite;
    text-align: center;
  }

  .features {
    display: grid;
    grid-template-columns: 1fr 1fr 1fr 1fr;
    padding: 1vh 1vw;
    margin: 3vh 1vw;
    justify-content: center;
    align-content: center;
  }

  .service-card {
    height: 80%;
    padding: 2em 1.5em;
    border-radius: 5px;
    box-shadow: 0 0 35px rgba(0, 0, 0, 0.12);
    cursor: pointer;
    transition: 0.5s;
    position: relative;
    z-index: 2;
    overflow: hidden;
    background: #fff;
    margin: 1vh 1vw;
  }

  h3 {
    font-size: 20px;
    text-transform: capitalize;
    font-weight: 600;
    color: #1f194c;
    margin: 1em 0;
    text-align: center;
    z-index: 3;
  }

  .icon-wrapper {
    position: relative;
    margin: auto;
    font-size: 30px;
    height: 2.5em;
    width: 2.5em;
    color: #ffffff;
    border-radius: 50%;
    display: grid;
    place-items: center;
    transition: 0.5s;
    z-index: 3;
    align-content: center;
    justify-content: center;
  }

  .icon-wrapper img {
    width: inherit;
    height: inherit;
  }

  @media screen and (max-width:1200px) {
    .features {
      display: grid;
      grid-template-columns: 1fr 1fr;
      padding: 1vh 1vw;
      margin: 3vh 1vw;
    }
  }

  @media screen and (max-width:400px) {
    .features {
      display: grid;
      grid-template-columns: 1fr;
      padding: 1vh 1vw;
      margin: 3vh 1vw;
    }
  }
</style>
<div class="index-container">
  {% if messages %}
  <p class="messages" style="display:flex;flex-direction: column;justify-content: center;align-items: center;">
    {% for message in messages %}
    {% if 'login_success' in message.tags %}
  <div class="alert alert-info alert-dismissible fade show js-alert" role="alert">
    {{ message }}
  </div>
  {% endif %}
  {% endfor %}
  </p>
  {% endif %}
  {% if user.is_authenticated %}
  <p class="username">Hello {{ user }}!</p>
  <p class="des">
    Welcome to the Logical Aptitude Challenge, a thrilling puzzle game designed
    to test and enhance your logical thinking skills.<br />Are you ready to
    embark on a journey of mind-bending puzzles and unravel the secrets of
    logic? <br />Put your problem-solving abilities to the test and see if you
    can conquer each challenge that awaits!
  </p>
  <form method="GET" action="{% url 'interactivepuzzle:instructions' %}">
    <button type="submit" class="btn btn-success">Take the assessment</button>
  </form>

  <div class="features">
    <div class="service-card">
      <div class="icon-wrapper">
        <img src="https://cdn.icon-icons.com/icons2/2474/PNG/512/puzzle_icon_149707.png"></img>
      </div>
      <h3>Engaging and Interactive Puzzles</h3>`
    </div>
    <div class="service-card">
      <div class="icon-wrapper">
        <img
          src="https://uploads-ssl.webflow.com/6046c7ac837ca2619771d513/62fc443397e4f6e98b6bb7d0_track-progress.png"></img>
      </div>
      <h3>Track Your Progress</h3>
    </div>
    <div class="service-card">
      <div class="icon-wrapper">
        <img
          src="https://img.freepik.com/premium-vector/person-choosing-answer-online-pensive-young-man-holding-tablet-while-giving-answers-online_697837-283.jpg?w=2000"></img>
      </div>
      <h3>Resume Anytime, Anywhere</h3>
    </div>
    <div class="service-card">
      <div class="icon-wrapper">
        <img
          src="https://static.vecteezy.com/system/resources/previews/000/644/965/original/vector-brain-light-bulb-icon.jpg"></img>
      </div>
      <h3>Sharpen Your Logical Aptitude</h3>
    </div>
  </div>
  {% endif %}
</div>
{% endblock %}

interactivepuzzle/templates/instructions.html
{% extends 'header.html' %} {% block content %}
<style>
  .int_container {
    width: 75vw;
    justify-content: center;
    align-items: center;
    display: flex;
    margin: 2vh auto;
    font-size: 1.1rem;
    min-height: 79vh;
  }
  .int_header {
    padding: 1vh 1vw;
    text-align: center;
    margin: 1vh 1vw;
    background-color: white;
    color: green;
    width: 95%;
  }
  .int_ul li {
    margin: 1vh 1vw;
    width: 95%;
    list-style: inside;
  }
  .int_form {
    display: flex;
    align-items: center;
    justify-content: center;
  }
  .int_button {
    width: 8vw;
  }
  .data {
    display: flex;
    align-items: center;
    justify-content: center;
    flex-direction: column;
  }
  
  @media screen and (max-width: 1200px) {
    .int_button {
      width: 25vw;
    }
  }
  @media screen and (max-width: 800px) {
    .int_button {
      width: 25vw;
    }
    .int_container {
      width: 100vw;
      margin: 1vh 1vw;
    }
  }
</style>
<div class="int_container">
  <div class="data">
    <h3 class="int_header">Instructions</h3>
    <ul class="int_ul">
      <li>
        The objective of this puzzle game is to solve a series of interactive
        puzzles and demonstrate your logical aptitude.
      </li>
      <li>
        If you haven't already registered, create an account on the website.
        Provide the required information and follow the registration process.
      </li>
      <li>
        Analyze the puzzle and use your logical thinking skills to find a
        solution. Depending on the puzzle type, you may need to arrange objects,
        find patterns, complete sequences, or make logical deductions.
      </li>
      <li>
        After completing the puzzle game, view your final score and see how you
        rank among other players. The score could be based on accuracy, speed,
        or a combination of factors.
      </li>
      <li>
        If you encounter a network issue, follow these steps to resume from
        where you left off:
        <ul>
          <li>Check your internet connection.</li>
          <li>Reload the page.</li>
          <li>Login again with your account.</li>
          <li>Your previous progress will be retrieved.</li>
        </ul>
      </li>
    </ul>
    <form
      class="int_form"
      method="GET"
      action="{%url 'interactivepuzzle:fetchquestion' %}"
    >
      <button type="submit" class="int_button btn btn-success">Proceed</button>
    </form>
  </div>
</div>

{% endblock %}

interactivepuzzle/templates/question.html
{% extends "header.html" %} {% block content %} {% load crispy_forms_tags %}
<style>
  @import url('https://fonts.googleapis.com/css?family=Open+Sans');

  .question_container {
    max-width: 600px;
    width: 90vw;
    background: #1A1A1A;
    color: #fff;
    border-radius: 10px;
    box-shadow: 0 2px 15px #1A1A1A66;
    display: flex;
    flex-direction: column;
    margin: 1vh auto;
    padding: 1rem 1.25rem;
  }

  .question_container figure {
    position: relative;
    margin: -1rem -1.25rem;
    position: relative;
    justify-content: center;
    margin: -1rem -1.25rem;
    align-items: center;
    display: flex;
  }

  .question_container figure img {
    border-radius: 10px 10px 0 0;
    width: 100%;
    filter: saturate(180%) brightness(0.8);
  }

  .form_button>button {
    margin: 3rem 0.25rem 1rem;
    align-self: center;
    color: #fff;
    background: #D31411;
    padding: 1rem 4.25rem;
    border: none;
    border-radius: 5px;
    text-transform: uppercase;
    letter-spacing: 0.1rem;
    font-weight: bold;
    font-family: inherit;
    transition: transform 0.2s cubic-bezier(0.34, .86, 0.58, 1.27);
    align-items: center;
    justify-content: center;
  }

  .form_button {
    justify-content: center;
    align-items: center;
  }

  .form_button>button:hover {
    transform: scale(1.15);
  }

  .question_container p {
    line-height: 1.5;
    font-weight: 600;
  }

  .question_container .answers {
    display: flex;
    flex-direction: column;
    margin: 1rem 0;
    width: 100%;
  }

  .question_container .answers button {
    text-align: left;
    color: inherit;
    background: rgba(255, 255, 255, 0.25);
    padding: 0.75rem 1rem;
    margin: 0.2rem 0;
    border: none;
    border-radius: 2px;
    font-family: inherit;
    font-weight: 500;
    text-transform: capitalize;
    font-size: 1rem;
    letter-spacing: 0.1rem;
    transition: all 0.1s ease-out;
    position: relative;
  }

  .question_container .answers button:hover {
    transform: scale(1.02);
    background: #D31411;
  }

  .question_container .answers button.correct {
    background: linear-gradient(to right, transparent 70%, rgba(0, 0, 0, 0.2) 70%), #5BC20F;
  }

  .question_container .answers button.selected {
    border-left: 4px solid #D31411;
    border-top-left-radius: 0;
    border-bottom-left-radius: 0;
  }

  .question_container .answers button:nth-child(1) {
    background: linear-gradient(to right, transparent 20%, rgba(0, 0, 0, 0.3) 20%), rgba(255, 255, 255, 0.25);
  }

  .form_button {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
  }

  .question_container .answers button span {
    position: absolute;
    top: 50%;
    right: 10px;
    transform: translate(0%, -50%);
    background: #fff;
    color: #1A1A1A;
    border-radius: 30px;
    padding: 0.4rem 0.5rem;
    font-size: 0.7rem;
    font-weight: 500;
    display: flex;
    justify-content: center;
    align-items: center;
  }

  .question_container .answers button:not(.correct) span:after {
    content: '%';
  }

  .question_container .answers button span svg {
    width: 25px;
    height: 15px;
  }

  .question_container .result {
    display: flex;
    align-items: flex-start;
    flex-wrap: wrap;
  }

  .question_container .result svg {
    width: 42px;
    height: 42px;
    margin-right: 8px;
  }

  .question_container .result h2 {
    color: #5BC20F;
    color: #D31411;
    letter-spacing: 0.05rem;
    font-size: 1.8rem;
    flex-grow: 1;
    display: flex;
    align-items: center;
  }

  .question_container .result h2:after {
    content: '!';
  }

  .question_container .result p {
    margin-top: 10px;
    max-width: 350px;
    line-height: 1.2;
    font-weight: initial;
  }

  .form_button input {
    padding: 1vh 1vw;
    width: 100%;
    border-radius: 10px;
    width: 100% !important;
  }
</style>

<section class="question_container">
  <figure>
    <img src="{{question.image}}" alt="Image for the Question">
  </figure>
</section>
<section class="question_container">
  {% if messages %}
  <p class="messages" style="display:flex;flex-direction: column;justify-content: center;align-items: center;">
    {% for message in messages %}
    {% if 'wrong_submission' in message.tags %}
  <div class="alert alert-info alert-dismissible fade show js-alert" role="alert">
    {{ message }}
  </div>
  {% endif %}
  {% endfor %}
  </p>
  {% endif %}
  <p style="text-align: center;">
    {{question.question_title}}
  </p>
  <p style="color:rgb(195, 195, 195)">{{question.question_text}} </p>
  <p>
  <h5 style="color:rgb(163, 163, 163)">Description:</h5> {{question.question_description}}
  </p>
  <div>
    <h5 style="color:rgb(13, 252, 5)">Clues:</h5>
    {% for clue in question.clues %}
    {% if forloop.counter != 1 %}
    <div>
      <p>⦿ {{ clue }}</p>
    </div>
    {% endif %}
    {% endfor %}
  </div>
  <form class="form_button" method="POST" action="{% url 'interactivepuzzle:submission' id=question.id %}">
    <div class="answers">
      {% csrf_token %}
      <input type="text" placeholder="Please Enter the Answer Here!" onkeyup="this.value = this.value.toUpperCase();"
        name="answer"></input>
    </div>
    <button method="submit">Submit</button>
  </form>
</section>
</div>

{% endblock %}